# yml型文件配置使用两个空格缩进，值和冒号中间一定要有空格
server:
  port: 8000
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=False&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
#    hibernate.ddl-auto: create  每次启动重新建表显然不可
    hibernate.ddl-auto: update


#management:
#  security:
#    enabled: false  //springboot2.0之后的版本不生效
